/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "F:\\lakei\\Vue\\lakeiedward's\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-546a8136",
    path: "/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-546a8136").then(next)
    },
  },
  {
    path: "/web/index.html",
    redirect: "/web/"
  },
  {
    path: "/00.目录页/01.前端.html",
    redirect: "/web/"
  },
  {
    name: "v-d7e8286a",
    path: "/frame/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d7e8286a").then(next)
    },
  },
  {
    path: "/frame/index.html",
    redirect: "/frame/"
  },
  {
    path: "/00.目录页/02.框架.html",
    redirect: "/frame/"
  },
  {
    name: "v-239a2dd2",
    path: "/comprehensive/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-239a2dd2").then(next)
    },
  },
  {
    path: "/comprehensive/index.html",
    redirect: "/comprehensive/"
  },
  {
    path: "/00.目录页/03.其他.html",
    redirect: "/comprehensive/"
  },
  {
    name: "v-cd46a930",
    path: "/more/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cd46a930").then(next)
    },
  },
  {
    path: "/more/index.html",
    redirect: "/more/"
  },
  {
    path: "/00.目录页/04.更多.html",
    redirect: "/more/"
  },
  {
    name: "v-16117212",
    path: "/note/html/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16117212").then(next)
    },
  },
  {
    path: "/note/html/index.html",
    redirect: "/note/html/"
  },
  {
    path: "/01.前端/10.学习专栏/01.《HTML》笔记.html",
    redirect: "/note/html/"
  },
  {
    name: "v-353232b4",
    path: "/ui/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-353232b4").then(next)
    },
  },
  {
    path: "/ui/index.html",
    redirect: "/ui/"
  },
  {
    path: "/00.目录页/05.组件.html",
    redirect: "/ui/"
  },
  {
    name: "v-3638167c",
    path: "/note/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3638167c").then(next)
    },
  },
  {
    path: "/note/css/index.html",
    redirect: "/note/css/"
  },
  {
    path: "/01.前端/10.学习专栏/02.《CSS》笔记.html",
    redirect: "/note/css/"
  },
  {
    name: "v-0bb1f77e",
    path: "/note/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0bb1f77e").then(next)
    },
  },
  {
    path: "/note/vue/index.html",
    redirect: "/note/vue/"
  },
  {
    path: "/01.前端/10.学习专栏/04.《Vue》笔记.html",
    redirect: "/note/vue/"
  },
  {
    name: "v-0d8e00dc",
    path: "/note/javascript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d8e00dc").then(next)
    },
  },
  {
    path: "/note/javascript/index.html",
    redirect: "/note/javascript/"
  },
  {
    path: "/01.前端/10.学习专栏/03.《JavaScript》笔记.html",
    redirect: "/note/javascript/"
  },
  {
    name: "v-59807a5d",
    path: "/note/specification/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59807a5d").then(next)
    },
  },
  {
    path: "/note/specification/index.html",
    redirect: "/note/specification/"
  },
  {
    path: "/01.前端/10.学习专栏/20.《规范》笔记.html",
    redirect: "/note/specification/"
  },
  {
    name: "v-777e013e",
    path: "/note/softSkill/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-777e013e").then(next)
    },
  },
  {
    path: "/note/softSkill/index.html",
    redirect: "/note/softSkill/"
  },
  {
    path: "/01.前端/10.学习专栏/30.《软技能》笔记.html",
    redirect: "/note/softSkill/"
  },
  {
    name: "v-eb288740",
    path: "/note/continuousDelivery/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eb288740").then(next)
    },
  },
  {
    path: "/note/continuousDelivery/index.html",
    redirect: "/note/continuousDelivery/"
  },
  {
    path: "/01.前端/10.学习专栏/35.《持续集成&交付&部署》笔记.html",
    redirect: "/note/continuousDelivery/"
  },
  {
    name: "v-16b8ba1d",
    path: "/note/element-ui/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16b8ba1d").then(next)
    },
  },
  {
    path: "/note/element-ui/index.html",
    redirect: "/note/element-ui/"
  },
  {
    path: "/01.前端/20.踩坑专栏/01.《Element-UI 实践系列》笔记.html",
    redirect: "/note/element-ui/"
  },
  {
    name: "v-4a2e23bc",
    path: "/note/mobile/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a2e23bc").then(next)
    },
  },
  {
    path: "/note/mobile/index.html",
    redirect: "/note/mobile/"
  },
  {
    path: "/01.前端/20.踩坑专栏/06.《移动端 实践系列》笔记.html",
    redirect: "/note/mobile/"
  },
  {
    name: "v-2367c592",
    path: "/note/complex/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2367c592").then(next)
    },
  },
  {
    path: "/note/complex/index.html",
    redirect: "/note/complex/"
  },
  {
    path: "/01.前端/20.踩坑专栏/07.《综合踩坑》笔记.html",
    redirect: "/note/complex/"
  },
  {
    name: "v-1f44305a",
    path: "/note/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f44305a").then(next)
    },
  },
  {
    path: "/note/git/index.html",
    redirect: "/note/git/"
  },
  {
    path: "/01.前端/20.踩坑专栏/10.《Git》笔记.html",
    redirect: "/note/git/"
  },
  {
    name: "v-0e794309",
    path: "/node/environment/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e794309").then(next)
    },
  },
  {
    path: "/node/environment/index.html",
    redirect: "/node/environment/"
  },
  {
    path: "/01.前端/30.配置专栏/30.《环境》笔记.html",
    redirect: "/node/environment/"
  },
  {
    name: "v-51e90f1d",
    path: "/node/interview/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51e90f1d").then(next)
    },
  },
  {
    path: "/node/interview/index.html",
    redirect: "/node/interview/"
  },
  {
    path: "/01.前端/40.面试专栏/01.《面试》笔记.html",
    redirect: "/node/interview/"
  },
  {
    name: "v-09595eb4",
    path: "/note/idea/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09595eb4").then(next)
    },
  },
  {
    path: "/note/idea/index.html",
    redirect: "/note/idea/"
  },
  {
    path: "/03.其他/01.《编辑器笔记》/01.《开发编辑器》笔记.html",
    redirect: "/note/idea/"
  },
  {
    name: "v-499cd320",
    path: "/pages/abfa54/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-499cd320").then(next)
    },
  },
  {
    path: "/pages/abfa54/index.html",
    redirect: "/pages/abfa54/"
  },
  {
    path: "/02.框架/30.高性能服务器 - Nginx/01.Nginx - 介绍.html",
    redirect: "/pages/abfa54/"
  },
  {
    name: "v-6bdc9a6a",
    path: "/note/browser/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bdc9a6a").then(next)
    },
  },
  {
    path: "/note/browser/index.html",
    redirect: "/note/browser/"
  },
  {
    path: "/03.其他/02.《浏览器笔记》/01.《Chrome》笔记.html",
    redirect: "/note/browser/"
  },
  {
    name: "v-2903043f",
    path: "/note/mac/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2903043f").then(next)
    },
  },
  {
    path: "/note/mac/index.html",
    redirect: "/note/mac/"
  },
  {
    path: "/03.其他/03.《Mac》笔记/01.《程序员的Mac》.html",
    redirect: "/note/mac/"
  },
  {
    name: "v-8f46e85a",
    path: "/navigation/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8f46e85a").then(next)
    },
  },
  {
    path: "/navigation/index.html",
    redirect: "/navigation/"
  },
  {
    path: "/01.导航站.html",
    redirect: "/navigation/"
  },
  {
    name: "v-12eef18c",
    path: "/note/cross-border/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12eef18c").then(next)
    },
  },
  {
    path: "/note/cross-border/index.html",
    redirect: "/note/cross-border/"
  },
  {
    path: "/03.其他/04.《跨界学习》笔记/01.《运营》.html",
    redirect: "/note/cross-border/"
  },
  {
    name: "v-f7593ec6",
    path: "/luckyui/home/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f7593ec6").then(next)
    },
  },
  {
    path: "/luckyui/home/index.html",
    redirect: "/luckyui/home/"
  },
  {
    path: "/04.luckyui/01.comonent/01.home.html",
    redirect: "/luckyui/home/"
  },
  {
    name: "v-273b2fb9",
    path: "/luckyui/button/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-273b2fb9").then(next)
    },
  },
  {
    path: "/luckyui/button/index.html",
    redirect: "/luckyui/button/"
  },
  {
    path: "/04.luckyui/01.comonent/02.button.html",
    redirect: "/luckyui/button/"
  },
  {
    name: "v-231679a5",
    path: "/whell/io/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-231679a5").then(next)
    },
  },
  {
    path: "/whell/io/index.html",
    redirect: "/whell/io/"
  },
  {
    path: "/70.收藏夹/20.我的/01.技术书籍.html",
    redirect: "/whell/io/"
  },
  {
    name: "v-221dd2eb",
    path: "/whell/book/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-221dd2eb").then(next)
    },
  },
  {
    path: "/whell/book/index.html",
    redirect: "/whell/book/"
  },
  {
    path: "/70.收藏夹/60.书单/01.技术书籍.html",
    redirect: "/whell/book/"
  },
  {
    name: "v-52dd7cce",
    path: "/whell/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52dd7cce").then(next)
    },
  },
  {
    path: "/whell/web/index.html",
    redirect: "/whell/web/"
  },
  {
    path: "/70.收藏夹/75.收藏夹/01.网站轮子.html",
    redirect: "/whell/web/"
  },
  {
    name: "v-b67b21fe",
    path: "/whell/front/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b67b21fe").then(next)
    },
  },
  {
    path: "/whell/front/index.html",
    redirect: "/whell/front/"
  },
  {
    path: "/70.收藏夹/75.收藏夹/02.前端轮子.html",
    redirect: "/whell/front/"
  },
  {
    name: "v-39affc7e",
    path: "/about/website/introduce/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39affc7e").then(next)
    },
  },
  {
    path: "/about/website/introduce/index.html",
    redirect: "/about/website/introduce/"
  },
  {
    path: "/80.关于/06.关于 - 本站/01.本站 - 介绍.html",
    redirect: "/about/website/introduce/"
  },
  {
    name: "v-42a4bba8",
    path: "/about/website/tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42a4bba8").then(next)
    },
  },
  {
    path: "/about/website/tools/index.html",
    redirect: "/about/website/tools/"
  },
  {
    path: "/80.关于/06.关于 - 本站/24.本站 - 导航站模块.html",
    redirect: "/about/website/tools/"
  },
  {
    name: "v-5f0bd641",
    path: "/whell/mac-software/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f0bd641").then(next)
    },
  },
  {
    path: "/whell/mac-software/index.html",
    redirect: "/whell/mac-software/"
  },
  {
    path: "/70.收藏夹/75.收藏夹/03.Mac软件.html",
    redirect: "/whell/mac-software/"
  },
  {
    name: "v-04cc55ae",
    path: "/about/website/code-block-hidden/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04cc55ae").then(next)
    },
  },
  {
    path: "/about/website/code-block-hidden/index.html",
    redirect: "/about/website/code-block-hidden/"
  },
  {
    path: "/80.关于/06.关于 - 本站/28.本站 - 代码块隐藏模块.html",
    redirect: "/about/website/code-block-hidden/"
  },
  {
    name: "v-af537e6e",
    path: "/pages/2f8f50/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-af537e6e").then(next)
    },
  },
  {
    path: "/pages/2f8f50/index.html",
    redirect: "/pages/2f8f50/"
  },
  {
    path: "/80.关于/08.关于 - 技巧/02.技巧 - 笔记.html",
    redirect: "/pages/2f8f50/"
  },
  {
    name: "v-74311f88",
    path: "/pages/f2a556/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74311f88").then(next)
    },
  },
  {
    path: "/pages/f2a556/index.html",
    redirect: "/pages/f2a556/"
  },
  {
    path: "/99.更多/01.学习/00.费曼学习法.html",
    redirect: "/pages/f2a556/"
  },
  {
    name: "v-c779f1ae",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c779f1ae").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    path: "/80.关于/03.关于 - 自我/01.自我 - 关于.html",
    redirect: "/about/"
  },
  {
    name: "v-f7cb13ea",
    path: "/pages/aea6571b7a8bae86/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f7cb13ea").then(next)
    },
  },
  {
    path: "/pages/aea6571b7a8bae86/index.html",
    redirect: "/pages/aea6571b7a8bae86/"
  },
  {
    path: "/99.更多/03.面试/01.面试问题集锦.html",
    redirect: "/pages/aea6571b7a8bae86/"
  },
  {
    name: "v-5ca75b77",
    path: "/pages/baaa02/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ca75b77").then(next)
    },
  },
  {
    path: "/pages/baaa02/index.html",
    redirect: "/pages/baaa02/"
  },
  {
    path: "/99.更多/10.实用技巧/01.2分钟规则.html",
    redirect: "/pages/baaa02/"
  },
  {
    name: "v-cf5696d8",
    path: "/archives/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cf5696d8").then(next)
    },
  },
  {
    path: "/archives/index.html",
    redirect: "/archives/"
  },
  {
    path: "/@pages/archivesPage.html",
    redirect: "/archives/"
  },
  {
    name: "v-a900df18",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a900df18").then(next)
    },
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    path: "/@pages/categoriesPage.html",
    redirect: "/categories/"
  },
  {
    name: "v-2e40cdd8",
    path: "/tags/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e40cdd8").then(next)
    },
  },
  {
    path: "/tags/index.html",
    redirect: "/tags/"
  },
  {
    path: "/@pages/tagsPage.html",
    redirect: "/tags/"
  },
  {
    name: "v-33a331a0",
    path: "/pages/9ccd26/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33a331a0").then(next)
    },
  },
  {
    path: "/pages/9ccd26/index.html",
    redirect: "/pages/9ccd26/"
  },
  {
    path: "/_posts/生活小记/01.《小狗钱钱》读书笔记.html",
    redirect: "/pages/9ccd26/"
  },
  {
    name: "v-07372183",
    path: "/pages/165d68/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07372183").then(next)
    },
  },
  {
    path: "/pages/165d68/index.html",
    redirect: "/pages/165d68/"
  },
  {
    path: "/_posts/生活小记/02.《富爸爸穷爸爸》穷人思维和富人思维有什么区别呢？.html",
    redirect: "/pages/165d68/"
  },
  {
    name: "v-9901ddb2",
    path: "/pages/0af0a3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9901ddb2").then(next)
    },
  },
  {
    path: "/pages/0af0a3/index.html",
    redirect: "/pages/0af0a3/"
  },
  {
    path: "/_posts/随笔/01.自我所认知的自律.html",
    redirect: "/pages/0af0a3/"
  },
  {
    name: "v-0bb031ce",
    path: "/pages/f2e63f/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0bb031ce").then(next)
    },
  },
  {
    path: "/pages/f2e63f/index.html",
    redirect: "/pages/f2e63f/"
  },
  {
    path: "/_posts/随笔/你知道的越多，不知道的也就越多.html",
    redirect: "/pages/f2e63f/"
  },
  {
    name: "v-cc47e8ce",
    path: "/pages/cd8bde/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cc47e8ce").then(next)
    },
  },
  {
    path: "/pages/cd8bde/index.html",
    redirect: "/pages/cd8bde/"
  },
  {
    path: "/_posts/随笔/拥抱生活，拥抱快乐.html",
    redirect: "/pages/cd8bde/"
  },
  {
    name: "v-64593500",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64593500").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]